const bcrypt = require('bcrypt');

// fonction pour hasher un mot de passe
export const hashPassword = (password: string) => {
    return bcrypt.hashSync(password, 10);
}

// fonction pour comparer un mot de passe avec son équivalent haché
export const comparePassword = (password: string, hashedPassword: string) => {
    return bcrypt.compareSync(password, hashedPassword);
}

const data = [
    {
        "idMembre": 1,
        "nomMembre": "Aya",
        "prenomMembre": "Jeanne Fidèle",
        "dateNaissMembre": "1997-11-30T00:00:00.000Z",
        "lieuNaissMembre": "Lieu 3",
        "sexeMembre": "F",
        "emailMembre": "email3@example.com",
        "nationaliteMembre": "Ivoirienne",
        "fonctionMembre": "0574313410",
        "contactMembre": "Contact 1",
        "ethnieMembre": "Bété",
        "residenceMembre": "Sicogi",
        "civiliteMembre": "Monsieur",
        "dateConversionMembre": "2005-09-10T00:00:00.000Z",
        "baptemeEauMembre": "OUI",
        "dateBaptemeMembre": "2010-03-18T00:00:00.000Z",
        "dateMariageMembre": null,
        "capaciteSpirituelleMembre": "Bonne",
        "situationMatrimonialeMembre": "Célibataire",
        "nombreEnfantMembre": 0,
        "photoMembre": null,
        "lieuBaptemeEauMembre": "Lieu Bapteme 3",
        "contactParentMembre": "Contact Parent 3",
        "baptemeSaintEspritMembre": "OUI",
        "dateBaptemeSaintEspritMembre": "2015-11-22T00:00:00.000Z",
        "egliseOrigineMembre": "Église Origine 3",
        "nomPrenomParentMembre": "Parent 3",
        "lieuTravailMembre": "Lieu Travail 3",
        "idNiveauEtude": 1,
        "idEglise": 2,
        "idCellule": null,
        "idDepartement": null,
        "idGroupe": null,
        "idResponsabilite": null,
        "idDomaineActivite": null,
        "idUtilisateur": null
    },
    {
        "idMembre": 2,
        "nomMembre": "Kamara",
        "prenomMembre": "keita kader",
        "dateNaissMembre": "2000-05-30T00:00:00.000Z",
        "lieuNaissMembre": "MAN",
        "sexeMembre": "M",
        "emailMembre": "keita@gmail.com",
        "nationaliteMembre": "Ivoirienne",
        "fonctionMembre": "057845222",
        "contactMembre": "Contact 2",
        "ethnieMembre": "Gouro",
        "residenceMembre": "Résidence 3",
        "civiliteMembre": "Monsieur",
        "dateConversionMembre": "2005-09-10T00:00:00.000Z",
        "baptemeEauMembre": "OUI",
        "dateBaptemeMembre": "2010-03-18T00:00:00.000Z",
        "dateMariageMembre": null,
        "capaciteSpirituelleMembre": "Capacité 3",
        "situationMatrimonialeMembre": "Célibataire",
        "nombreEnfantMembre": 0,
        "photoMembre": null,
        "lieuBaptemeEauMembre": "yop gare",
        "contactParentMembre": "0789815111",
        "baptemeSaintEspritMembre": "OUI",
        "dateBaptemeSaintEspritMembre": "2015-11-22T00:00:00.000Z",
        "egliseOrigineMembre": "Methodiste",
        "nomPrenomParentMembre": "Kamara Seydou",
        "lieuTravailMembre": "Zone Industrielle",
        "idNiveauEtude": null,
        "idEglise": 2,
        "idCellule": null,
        "idDepartement": null,
        "idGroupe": null,
        "idResponsabilite": null,
        "idDomaineActivite": null,
        "idUtilisateur": 4
    },
    {
        "idMembre": 4,
        "nomMembre": "Obrou",
        "prenomMembre": "Samuel",
        "dateNaissMembre": "1988-11-30T00:00:00.000Z",
        "lieuNaissMembre": "Lieu 3",
        "sexeMembre": "M",
        "emailMembre": "email3@example.com",
        "nationaliteMembre": "Nationalité 3",
        "fonctionMembre": "Fonction 3",
        "contactMembre": "Contact 3",
        "ethnieMembre": "Ethnie 3",
        "residenceMembre": "Résidence 3",
        "civiliteMembre": "Monsieur",
        "dateConversionMembre": "2005-09-10T00:00:00.000Z",
        "baptemeEauMembre": "OUI",
        "dateBaptemeMembre": "2010-03-18T00:00:00.000Z",
        "dateMariageMembre": null,
        "capaciteSpirituelleMembre": "Capacité 3",
        "situationMatrimonialeMembre": "Célibataire",
        "nombreEnfantMembre": 0,
        "photoMembre": null,
        "lieuBaptemeEauMembre": "Lieu Bapteme 3",
        "contactParentMembre": "Contact Parent 3",
        "baptemeSaintEspritMembre": "OUI",
        "dateBaptemeSaintEspritMembre": "2015-11-22T00:00:00.000Z",
        "egliseOrigineMembre": "Église Origine 3",
        "nomPrenomParentMembre": "Parent 3",
        "lieuTravailMembre": "Lieu Travail 3",
        "idNiveauEtude": null,
        "idEglise": null,
        "idCellule": null,
        "idDepartement": null,
        "idGroupe": null,
        "idResponsabilite": null,
        "idDomaineActivite": null,
        "idUtilisateur": 1
    },
    {
        "idMembre": 5,
        "nomMembre": "Aya",
        "prenomMembre": "Jeanne Fidèle",
        "dateNaissMembre": "1997-11-30T00:00:00.000Z",
        "lieuNaissMembre": "Aboisso",
        "sexeMembre": "F",
        "emailMembre": "email3@example.com",
        "nationaliteMembre": "Ivoirienne",
        "fonctionMembre": "0789552011",
        "contactMembre": "Contact 3",
        "ethnieMembre": "Bété",
        "residenceMembre": "Sicogi",
        "civiliteMembre": "Monsieur",
        "dateConversionMembre": "2005-09-10T00:00:00.000Z",
        "baptemeEauMembre": "OUI",
        "dateBaptemeMembre": "2010-03-18T00:00:00.000Z",
        "dateMariageMembre": null,
        "capaciteSpirituelleMembre": "Bonne",
        "situationMatrimonialeMembre": "Célibataire",
        "nombreEnfantMembre": 0,
        "photoMembre": null,
        "lieuBaptemeEauMembre": "Lieu Bapteme 3",
        "contactParentMembre": "Contact Parent 3",
        "baptemeSaintEspritMembre": "OUI",
        "dateBaptemeSaintEspritMembre": "2015-11-22T00:00:00.000Z",
        "egliseOrigineMembre": "Assemblée de Dieu",
        "nomPrenomParentMembre": "Parent 3",
        "lieuTravailMembre": "Lieu Travail 3",
        "idNiveauEtude": 1,
        "idEglise": 1,
        "idCellule": 2,
        "idDepartement": 1,
        "idGroupe": 2,
        "idResponsabilite": null,
        "idDomaineActivite": 2,
        "idUtilisateur": 3
    },
    {
        "idMembre": 6,
        "nomMembre": "DOUA",
        "prenomMembre": "Bhi Hugues cyriaque",
        "dateNaissMembre": "1988-11-30T00:00:00.000Z",
        "lieuNaissMembre": "Andokoi",
        "sexeMembre": "M",
        "emailMembre": "hugues@gmail.com",
        "nationaliteMembre": "Nationalité 3",
        "fonctionMembre": "Fonction 3",
        "contactMembre": "Contact 3",
        "ethnieMembre": "Ethnie 3",
        "residenceMembre": "Résidence 3",
        "civiliteMembre": "Monsieur",
        "dateConversionMembre": "2005-09-10T00:00:00.000Z",
        "baptemeEauMembre": "OUI",
        "dateBaptemeMembre": "2010-03-18T00:00:00.000Z",
        "dateMariageMembre": null,
        "capaciteSpirituelleMembre": "Capacité 3",
        "situationMatrimonialeMembre": "Célibataire",
        "nombreEnfantMembre": 0,
        "photoMembre": null,
        "lieuBaptemeEauMembre": "Lieu Bapteme 3",
        "contactParentMembre": "Contact Parent 3",
        "baptemeSaintEspritMembre": "OUI",
        "dateBaptemeSaintEspritMembre": "2015-11-22T00:00:00.000Z",
        "egliseOrigineMembre": "Église Origine 3",
        "nomPrenomParentMembre": "Parent 3",
        "lieuTravailMembre": "Lieu Travail 3",
        "idNiveauEtude": null,
        "idEglise": null,
        "idCellule": null,
        "idDepartement": null,
        "idGroupe": null,
        "idResponsabilite": null,
        "idDomaineActivite": null,
        "idUtilisateur": 2
    },
    {
        "idMembre": 14,
        "nomMembre": "KOUASSI",
        "prenomMembre": "Sephoragh",
        "dateNaissMembre": "1998-05-15T00:00:00.000Z",
        "lieuNaissMembre": "Andokoi1",
        "sexeMembre": "M",
        "emailMembre": "hugues@gmail.com",
        "nationaliteMembre": "Ivoirienne",
        "fonctionMembre": "Etudiante",
        "contactMembre": "Contact 3",
        "ethnieMembre": "Ethnie 3",
        "residenceMembre": "Résidence 3",
        "civiliteMembre": "Monsieur",
        "dateConversionMembre": "2005-09-10T00:00:00.000Z",
        "baptemeEauMembre": "OUI",
        "dateBaptemeMembre": "2005-09-10T00:00:00.000Z",
        "dateMariageMembre": null,
        "capaciteSpirituelleMembre": "Capacité 3",
        "situationMatrimonialeMembre": "Célibataire",
        "nombreEnfantMembre": 0,
        "photoMembre": null,
        "lieuBaptemeEauMembre": "Lieu Bapteme 3",
        "contactParentMembre": "Contact Parent 3",
        "baptemeSaintEspritMembre": "Oui",
        "dateBaptemeSaintEspritMembre": "2005-09-10T00:00:00.000Z",
        "egliseOrigineMembre": "Église Origine 1",
        "nomPrenomParentMembre": "Parent 1",
        "lieuTravailMembre": "Lieu Travail 1",
        "idNiveauEtude": null,
        "idEglise": null,
        "idCellule": null,
        "idDepartement": null,
        "idGroupe": null,
        "idResponsabilite": null,
        "idDomaineActivite": null,
        "idUtilisateur": null
    },
    {
        "idMembre": 15,
        "nomMembre": "KOUASSI",
        "prenomMembre": "Sephora",
        "dateNaissMembre": "1998-05-15T00:00:00.000Z",
        "lieuNaissMembre": "Andokoi",
        "sexeMembre": "M",
        "emailMembre": "hugues@gmail.com",
        "nationaliteMembre": "Ivoirienne",
        "fonctionMembre": "Etudiante",
        "contactMembre": "Contact 3",
        "ethnieMembre": "Ethnie 3",
        "residenceMembre": "Résidence 3",
        "civiliteMembre": "Monsieur",
        "dateConversionMembre": "2005-09-10T00:00:00.000Z",
        "baptemeEauMembre": "OUI",
        "dateBaptemeMembre": "2005-09-10T00:00:00.000Z",
        "dateMariageMembre": null,
        "capaciteSpirituelleMembre": "Capacité 3",
        "situationMatrimonialeMembre": "Célibataire",
        "nombreEnfantMembre": 0,
        "photoMembre": null,
        "lieuBaptemeEauMembre": "Lieu Bapteme 3",
        "contactParentMembre": "Contact Parent 3",
        "baptemeSaintEspritMembre": "Oui",
        "dateBaptemeSaintEspritMembre": "2005-09-10T00:00:00.000Z",
        "egliseOrigineMembre": "Église Origine 1",
        "nomPrenomParentMembre": "Parent 1",
        "lieuTravailMembre": "Lieu Travail 1",
        "idNiveauEtude": null,
        "idEglise": null,
        "idCellule": null,
        "idDepartement": null,
        "idGroupe": null,
        "idResponsabilite": null,
        "idDomaineActivite": null,
        "idUtilisateur": null
    },
    {
        "idMembre": 16,
        "nomMembre": "KOUASSI",
        "prenomMembre": "Sephora",
        "dateNaissMembre": "1998-05-15T00:00:00.000Z",
        "lieuNaissMembre": "Andokoi",
        "sexeMembre": "M",
        "emailMembre": "hugues@gmail.com",
        "nationaliteMembre": "Ivoirienne",
        "fonctionMembre": "Etudiante",
        "contactMembre": "Contact 3",
        "ethnieMembre": "Ethnie 3",
        "residenceMembre": "Résidence 3",
        "civiliteMembre": "Monsieur",
        "dateConversionMembre": "2005-09-10T00:00:00.000Z",
        "baptemeEauMembre": "OUI",
        "dateBaptemeMembre": "2005-09-10T00:00:00.000Z",
        "dateMariageMembre": null,
        "capaciteSpirituelleMembre": "Capacité 3",
        "situationMatrimonialeMembre": "Célibataire",
        "nombreEnfantMembre": 0,
        "photoMembre": null,
        "lieuBaptemeEauMembre": "Lieu Bapteme 3",
        "contactParentMembre": "Contact Parent 3",
        "baptemeSaintEspritMembre": "Oui",
        "dateBaptemeSaintEspritMembre": "2005-09-10T00:00:00.000Z",
        "egliseOrigineMembre": "Église Origine 1",
        "nomPrenomParentMembre": "Parent 1",
        "lieuTravailMembre": "Lieu Travail 1",
        "idNiveauEtude": null,
        "idEglise": null,
        "idCellule": null,
        "idDepartement": null,
        "idGroupe": null,
        "idResponsabilite": null,
        "idDomaineActivite": null,
        "idUtilisateur": null
    },
    {
        "idMembre": 21,
        "nomMembre": "Ouattara",
        "prenomMembre": "Marie Joel",
        "dateNaissMembre": "1995-05-30T00:00:00.000Z",
        "lieuNaissMembre": "Aboisso",
        "sexeMembre": "M",
        "emailMembre": "marie@gmail.com",
        "nationaliteMembre": "Ivoirienne",
        "fonctionMembre": "Professeur",
        "contactMembre": "057845222",
        "ethnieMembre": "Gouro",
        "residenceMembre": "Résidence 3",
        "civiliteMembre": "Monsieur",
        "dateConversionMembre": "2005-09-10T00:00:00.000Z",
        "baptemeEauMembre": "OUI",
        "dateBaptemeMembre": "2010-03-18T00:00:00.000Z",
        "dateMariageMembre": null,
        "capaciteSpirituelleMembre": "Capacité 3",
        "situationMatrimonialeMembre": "Célibataire",
        "nombreEnfantMembre": 0,
        "photoMembre": null,
        "lieuBaptemeEauMembre": "yop gare",
        "contactParentMembre": "Contact Parent 3",
        "baptemeSaintEspritMembre": "OUI",
        "dateBaptemeSaintEspritMembre": "2015-11-22T00:00:00.000Z",
        "egliseOrigineMembre": "Église Origine 3",
        "nomPrenomParentMembre": "Parent 3",
        "lieuTravailMembre": "Lieu Travail 3",
        "idNiveauEtude": null,
        "idEglise": null,
        "idCellule": null,
        "idDepartement": null,
        "idGroupe": null,
        "idResponsabilite": null,
        "idDomaineActivite": null,
        "idUtilisateur": 4
    },
    {
        "idMembre": 22,
        "nomMembre": "Coulibali",
        "prenomMembre": "Seydou Jean Pierre",
        "dateNaissMembre": "1997-05-30T00:00:00.000Z",
        "lieuNaissMembre": "MAN",
        "sexeMembre": "M",
        "emailMembre": "coulibali@gmail.com",
        "nationaliteMembre": "Ivoirienne",
        "fonctionMembre": "Professeur",
        "contactMembre": "057845222",
        "ethnieMembre": "Gouro",
        "residenceMembre": "Résidence 3",
        "civiliteMembre": "Monsieur",
        "dateConversionMembre": "2005-09-10T00:00:00.000Z",
        "baptemeEauMembre": "OUI",
        "dateBaptemeMembre": "2010-03-18T00:00:00.000Z",
        "dateMariageMembre": null,
        "capaciteSpirituelleMembre": "Capacité 3",
        "situationMatrimonialeMembre": "Célibataire",
        "nombreEnfantMembre": 0,
        "photoMembre": null,
        "lieuBaptemeEauMembre": "yop gare",
        "contactParentMembre": "Contact Parent 3",
        "baptemeSaintEspritMembre": "OUI",
        "dateBaptemeSaintEspritMembre": "2015-11-22T00:00:00.000Z",
        "egliseOrigineMembre": "Église Origine 3",
        "nomPrenomParentMembre": "Parent 3",
        "lieuTravailMembre": "Lieu Travail 3",
        "idNiveauEtude": null,
        "idEglise": null,
        "idCellule": null,
        "idDepartement": null,
        "idGroupe": null,
        "idResponsabilite": null,
        "idDomaineActivite": null,
        "idUtilisateur": 5
    },
    {
        "idMembre": 23,
        "nomMembre": "Coulibali",
        "prenomMembre": "Seydou Jean Pierre",
        "dateNaissMembre": "1997-05-30T00:00:00.000Z",
        "lieuNaissMembre": "MAN",
        "sexeMembre": "M",
        "emailMembre": "coulibali@gmail.com",
        "nationaliteMembre": "Ivoirienne",
        "fonctionMembre": "Professeur",
        "contactMembre": "057845222",
        "ethnieMembre": "Gouro",
        "residenceMembre": "Résidence 3",
        "civiliteMembre": "Monsieur",
        "dateConversionMembre": "2005-09-10T00:00:00.000Z",
        "baptemeEauMembre": "OUI",
        "dateBaptemeMembre": "2010-03-18T00:00:00.000Z",
        "dateMariageMembre": null,
        "capaciteSpirituelleMembre": "Capacité 3",
        "situationMatrimonialeMembre": "Célibataire",
        "nombreEnfantMembre": 0,
        "photoMembre": null,
        "lieuBaptemeEauMembre": "yop gare",
        "contactParentMembre": "Contact Parent 3",
        "baptemeSaintEspritMembre": "OUI",
        "dateBaptemeSaintEspritMembre": "2015-11-22T00:00:00.000Z",
        "egliseOrigineMembre": "Église Origine 3",
        "nomPrenomParentMembre": "Parent 3",
        "lieuTravailMembre": "Lieu Travail 3",
        "idNiveauEtude": null,
        "idEglise": null,
        "idCellule": null,
        "idDepartement": null,
        "idGroupe": null,
        "idResponsabilite": null,
        "idDomaineActivite": null,
        "idUtilisateur": 4
    },
    {
        "idMembre": 24,
        "nomMembre": "Adiobo",
        "prenomMembre": "Marie Paule",
        "dateNaissMembre": "1992-05-21T00:00:00.000Z",
        "lieuNaissMembre": "Toumodi",
        "sexeMembre": "M",
        "emailMembre": "mariepaule@gmail.com",
        "nationaliteMembre": "Ivoirienne",
        "fonctionMembre": "Directrice générale",
        "contactMembre": "0789854122",
        "ethnieMembre": "Baoulé",
        "residenceMembre": "Cocody angré",
        "civiliteMembre": "Mademoiselle",
        "dateConversionMembre": "2005-09-10T00:00:00.000Z",
        "baptemeEauMembre": "OUI",
        "dateBaptemeMembre": "2010-03-18T00:00:00.000Z",
        "dateMariageMembre": null,
        "capaciteSpirituelleMembre": "Bonne",
        "situationMatrimonialeMembre": "Célibataire",
        "nombreEnfantMembre": 0,
        "photoMembre": null,
        "lieuBaptemeEauMembre": "Yopougon gare",
        "contactParentMembre": "0564820016",
        "baptemeSaintEspritMembre": "OUI",
        "dateBaptemeSaintEspritMembre": "2016-11-22T00:00:00.000Z",
        "egliseOrigineMembre": "Église Origine 3",
        "nomPrenomParentMembre": "Parent 3",
        "lieuTravailMembre": "UEFHB",
        "idNiveauEtude": null,
        "idEglise": null,
        "idCellule": null,
        "idDepartement": null,
        "idGroupe": null,
        "idResponsabilite": null,
        "idDomaineActivite": null,
        "idUtilisateur": 1
    },
    {
        "idMembre": 25,
        "nomMembre": "Coulibali",
        "prenomMembre": "Seydou Jean Pierre",
        "dateNaissMembre": "2000-05-30T00:00:00.000Z",
        "lieuNaissMembre": "MAN",
        "sexeMembre": "M",
        "emailMembre": "coulibali@gmail.com",
        "nationaliteMembre": "Ivoirienne",
        "fonctionMembre": "Professeur",
        "contactMembre": "057845222",
        "ethnieMembre": "Gouro",
        "residenceMembre": "Résidence 3",
        "civiliteMembre": "Monsieur",
        "dateConversionMembre": "2005-09-10T00:00:00.000Z",
        "baptemeEauMembre": "OUI",
        "dateBaptemeMembre": "2010-03-18T00:00:00.000Z",
        "dateMariageMembre": null,
        "capaciteSpirituelleMembre": "Capacité 3",
        "situationMatrimonialeMembre": "Célibataire",
        "nombreEnfantMembre": 0,
        "photoMembre": null,
        "lieuBaptemeEauMembre": "yop gare",
        "contactParentMembre": "0789815111",
        "baptemeSaintEspritMembre": "OUI",
        "dateBaptemeSaintEspritMembre": "2015-11-22T00:00:00.000Z",
        "egliseOrigineMembre": "Église Origine 3",
        "nomPrenomParentMembre": "Parent 3",
        "lieuTravailMembre": "Lieu Travail 3",
        "idNiveauEtude": null,
        "idEglise": null,
        "idCellule": null,
        "idDepartement": null,
        "idGroupe": null,
        "idResponsabilite": null,
        "idDomaineActivite": null,
        "idUtilisateur": 2
    },
    {
        "idMembre": 26,
        "nomMembre": "N'dri",
        "prenomMembre": "Jean Luc",
        "dateNaissMembre": "2000-05-30T00:00:00.000Z",
        "lieuNaissMembre": "MAN",
        "sexeMembre": "M",
        "emailMembre": "coulibali@gmail.com",
        "nationaliteMembre": "Ivoirienne",
        "fonctionMembre": "Professeur",
        "contactMembre": "057845222",
        "ethnieMembre": "Gouro",
        "residenceMembre": "Résidence 3",
        "civiliteMembre": "Monsieur",
        "dateConversionMembre": "2005-09-10T00:00:00.000Z",
        "baptemeEauMembre": "OUI",
        "dateBaptemeMembre": "2010-03-18T00:00:00.000Z",
        "dateMariageMembre": null,
        "capaciteSpirituelleMembre": "Capacité 3",
        "situationMatrimonialeMembre": "Célibataire",
        "nombreEnfantMembre": 0,
        "photoMembre": null,
        "lieuBaptemeEauMembre": "yop gare",
        "contactParentMembre": "0789815111",
        "baptemeSaintEspritMembre": "OUI",
        "dateBaptemeSaintEspritMembre": "2015-11-22T00:00:00.000Z",
        "egliseOrigineMembre": "Église Origine 3",
        "nomPrenomParentMembre": "Parent 3",
        "lieuTravailMembre": "Zone Industrielle",
        "idNiveauEtude": null,
        "idEglise": null,
        "idCellule": null,
        "idDepartement": null,
        "idGroupe": null,
        "idResponsabilite": null,
        "idDomaineActivite": null,
        "idUtilisateur": null
    },
    {
        "idMembre": 27,
        "nomMembre": "Doumbia",
        "prenomMembre": "Soumailla",
        "dateNaissMembre": "2000-05-30T00:00:00.000Z",
        "lieuNaissMembre": "MAN",
        "sexeMembre": "M",
        "emailMembre": "coulibali@gmail.com",
        "nationaliteMembre": "Ivoirienne",
        "fonctionMembre": "Professeur",
        "contactMembre": "057845222",
        "ethnieMembre": "Gouro",
        "residenceMembre": "Résidence 3",
        "civiliteMembre": "Monsieur",
        "dateConversionMembre": "2005-09-10T00:00:00.000Z",
        "baptemeEauMembre": "OUI",
        "dateBaptemeMembre": "2010-03-18T00:00:00.000Z",
        "dateMariageMembre": null,
        "capaciteSpirituelleMembre": "Capacité 3",
        "situationMatrimonialeMembre": "Célibataire",
        "nombreEnfantMembre": 0,
        "photoMembre": null,
        "lieuBaptemeEauMembre": "yop gare",
        "contactParentMembre": "0789815111",
        "baptemeSaintEspritMembre": "OUI",
        "dateBaptemeSaintEspritMembre": "2015-11-22T00:00:00.000Z",
        "egliseOrigineMembre": "Église Origine 3",
        "nomPrenomParentMembre": "Parent 3",
        "lieuTravailMembre": "Zone Industrielle",
        "idNiveauEtude": null,
        "idEglise": null,
        "idCellule": null,
        "idDepartement": null,
        "idGroupe": null,
        "idResponsabilite": null,
        "idDomaineActivite": null,
        "idUtilisateur": null
    },
    {
        "idMembre": 28,
        "nomMembre": "Doumbia",
        "prenomMembre": "Soumailla",
        "dateNaissMembre": "2000-05-30T00:00:00.000Z",
        "lieuNaissMembre": "MAN",
        "sexeMembre": "M",
        "emailMembre": "coulibali@gmail.com",
        "nationaliteMembre": "Ivoirienne",
        "fonctionMembre": "Professeur",
        "contactMembre": "057845222",
        "ethnieMembre": "Gouro",
        "residenceMembre": "Résidence 3",
        "civiliteMembre": "Monsieur",
        "dateConversionMembre": "2005-09-10T00:00:00.000Z",
        "baptemeEauMembre": "OUI",
        "dateBaptemeMembre": "2010-03-18T00:00:00.000Z",
        "dateMariageMembre": null,
        "capaciteSpirituelleMembre": "Capacité 3",
        "situationMatrimonialeMembre": "Célibataire",
        "nombreEnfantMembre": 0,
        "photoMembre": null,
        "lieuBaptemeEauMembre": "yop gare",
        "contactParentMembre": "0789815111",
        "baptemeSaintEspritMembre": "OUI",
        "dateBaptemeSaintEspritMembre": "2015-11-22T00:00:00.000Z",
        "egliseOrigineMembre": "Église Origine 3",
        "nomPrenomParentMembre": "Parent 3",
        "lieuTravailMembre": "Zone Industrielle",
        "idNiveauEtude": 10,
        "idEglise": 5,
        "idCellule": 1,
        "idDepartement": null,
        "idGroupe": null,
        "idResponsabilite": null,
        "idDomaineActivite": null,
        "idUtilisateur": null
    },
    {
        "idMembre": 29,
        "nomMembre": "Kamara",
        "prenomMembre": "keita kader",
        "dateNaissMembre": "2000-05-30T00:00:00.000Z",
        "lieuNaissMembre": "MAN",
        "sexeMembre": "M",
        "emailMembre": "keita@gmail.com",
        "nationaliteMembre": "Ivoirienne",
        "fonctionMembre": "Professeur",
        "contactMembre": "057845222",
        "ethnieMembre": "Gouro",
        "residenceMembre": "Résidence 3",
        "civiliteMembre": "Monsieur",
        "dateConversionMembre": "2005-09-10T00:00:00.000Z",
        "baptemeEauMembre": "OUI",
        "dateBaptemeMembre": "2010-03-18T00:00:00.000Z",
        "dateMariageMembre": null,
        "capaciteSpirituelleMembre": "Capacité 3",
        "situationMatrimonialeMembre": "Célibataire",
        "nombreEnfantMembre": 0,
        "photoMembre": null,
        "lieuBaptemeEauMembre": "yop gare",
        "contactParentMembre": "0789815111",
        "baptemeSaintEspritMembre": "OUI",
        "dateBaptemeSaintEspritMembre": "2015-11-22T00:00:00.000Z",
        "egliseOrigineMembre": "Methodiste",
        "nomPrenomParentMembre": "Parent 3",
        "lieuTravailMembre": "Zone Industrielle",
        "idNiveauEtude": 5,
        "idEglise": 4,
        "idCellule": 2,
        "idDepartement": null,
        "idGroupe": null,
        "idResponsabilite": null,
        "idDomaineActivite": null,
        "idUtilisateur": null
    },
    {
        "idMembre": 30,
        "nomMembre": "Ouattara",
        "prenomMembre": "Abdoul kader",
        "dateNaissMembre": "1998-05-15T00:00:00.000Z",
        "lieuNaissMembre": "Andokoi",
        "sexeMembre": "M",
        "emailMembre": "hugues@gmail.com",
        "nationaliteMembre": "Ivoirienne",
        "fonctionMembre": "Etudiante",
        "contactMembre": "0789815111",
        "ethnieMembre": "Senoufo",
        "residenceMembre": "Andokoi",
        "civiliteMembre": "Monsieur",
        "dateConversionMembre": "2005-09-10T00:00:00.000Z",
        "baptemeEauMembre": "OUI",
        "dateBaptemeMembre": "2005-09-10T00:00:00.000Z",
        "dateMariageMembre": null,
        "capaciteSpirituelleMembre": "Capacité 3",
        "situationMatrimonialeMembre": "Célibataire",
        "nombreEnfantMembre": 0,
        "photoMembre": null,
        "lieuBaptemeEauMembre": "Lieu Bapteme 3",
        "contactParentMembre": "Contact Parent 3",
        "baptemeSaintEspritMembre": "Oui",
        "dateBaptemeSaintEspritMembre": "2005-09-10T00:00:00.000Z",
        "egliseOrigineMembre": "Methodiste",
        "nomPrenomParentMembre": "Parent 1",
        "lieuTravailMembre": "Lieu Travail 1",
        "idNiveauEtude": null,
        "idEglise": null,
        "idCellule": null,
        "idDepartement": null,
        "idGroupe": null,
        "idResponsabilite": null,
        "idDomaineActivite": null,
        "idUtilisateur": 3
    },
    {
        "idMembre": 31,
        "nomMembre": "DIGBEU",
        "prenomMembre": "EDY STEPHANE",
        "dateNaissMembre": "1997-11-30T00:00:00.000Z",
        "lieuNaissMembre": "YACOLO",
        "sexeMembre": "F",
        "emailMembre": "email3@example.com",
        "nationaliteMembre": "Ivoirienne",
        "fonctionMembre": "0574313410",
        "contactMembre": "Contact 1",
        "ethnieMembre": "Bété",
        "residenceMembre": "Sicogi",
        "civiliteMembre": "Monsieur",
        "dateConversionMembre": "2005-09-10T00:00:00.000Z",
        "baptemeEauMembre": "OUI",
        "dateBaptemeMembre": "2010-03-18T00:00:00.000Z",
        "dateMariageMembre": null,
        "capaciteSpirituelleMembre": "Bonne",
        "situationMatrimonialeMembre": "Célibataire",
        "nombreEnfantMembre": 0,
        "photoMembre": null,
        "lieuBaptemeEauMembre": "YOP GARE",
        "contactParentMembre": "Contact Parent 3",
        "baptemeSaintEspritMembre": "OUI",
        "dateBaptemeSaintEspritMembre": "2015-11-22T00:00:00.000Z",
        "egliseOrigineMembre": "Église Origine 3",
        "nomPrenomParentMembre": "Parent 3",
        "lieuTravailMembre": "SPIDER TECHNOLOGIES",
        "idNiveauEtude": null,
        "idEglise": null,
        "idCellule": null,
        "idDepartement": null,
        "idGroupe": null,
        "idResponsabilite": null,
        "idDomaineActivite": null,
        "idUtilisateur": 2
    },
    {
        "idMembre": 33,
        "nomMembre": "DIGBEU",
        "prenomMembre": "EDY STEPHANE",
        "dateNaissMembre": "1997-11-30T00:00:00.000Z",
        "lieuNaissMembre": "YACOLO",
        "sexeMembre": "F",
        "emailMembre": "email3@example.com",
        "nationaliteMembre": "Ivoirienne",
        "fonctionMembre": "0574313410",
        "contactMembre": "Contact 1",
        "ethnieMembre": "Bété",
        "residenceMembre": "Sicogi",
        "civiliteMembre": "Monsieur",
        "dateConversionMembre": "2005-09-10T00:00:00.000Z",
        "baptemeEauMembre": "OUI",
        "dateBaptemeMembre": "2010-03-18T00:00:00.000Z",
        "dateMariageMembre": null,
        "capaciteSpirituelleMembre": "Bonne",
        "situationMatrimonialeMembre": "Célibataire",
        "nombreEnfantMembre": 0,
        "photoMembre": null,
        "lieuBaptemeEauMembre": "YOP GARE",
        "contactParentMembre": "Contact Parent 3",
        "baptemeSaintEspritMembre": "OUI",
        "dateBaptemeSaintEspritMembre": "2015-11-22T00:00:00.000Z",
        "egliseOrigineMembre": "Église Origine 3",
        "nomPrenomParentMembre": "Parent 3",
        "lieuTravailMembre": "SPIDER TECHNOLOGIES",
        "idNiveauEtude": null,
        "idEglise": null,
        "idCellule": null,
        "idDepartement": null,
        "idGroupe": null,
        "idResponsabilite": null,
        "idDomaineActivite": null,
        "idUtilisateur": null
    },
    {
        "idMembre": 34,
        "nomMembre": "DIGBEU",
        "prenomMembre": "EDY STEPHANE",
        "dateNaissMembre": "1997-11-30T00:00:00.000Z",
        "lieuNaissMembre": "YACOLO",
        "sexeMembre": "F",
        "emailMembre": "email3@example.com",
        "nationaliteMembre": "Ivoirienne",
        "fonctionMembre": "0574313410",
        "contactMembre": "Contact 1",
        "ethnieMembre": "Bété",
        "residenceMembre": "Sicogi",
        "civiliteMembre": "Monsieur",
        "dateConversionMembre": "2005-09-10T00:00:00.000Z",
        "baptemeEauMembre": "OUI",
        "dateBaptemeMembre": "2010-03-18T00:00:00.000Z",
        "dateMariageMembre": null,
        "capaciteSpirituelleMembre": "Bonne",
        "situationMatrimonialeMembre": "Célibataire",
        "nombreEnfantMembre": 0,
        "photoMembre": null,
        "lieuBaptemeEauMembre": "YOP GARE",
        "contactParentMembre": "Contact Parent 3",
        "baptemeSaintEspritMembre": "OUI",
        "dateBaptemeSaintEspritMembre": "2015-11-22T00:00:00.000Z",
        "egliseOrigineMembre": "Église Origine 3",
        "nomPrenomParentMembre": "Parent 3",
        "lieuTravailMembre": "SPIDER TECHNOLOGIES",
        "idNiveauEtude": null,
        "idEglise": null,
        "idCellule": null,
        "idDepartement": null,
        "idGroupe": null,
        "idResponsabilite": null,
        "idDomaineActivite": null,
        "idUtilisateur": null
    },
    {
        "idMembre": 35,
        "nomMembre": "DIGBEU",
        "prenomMembre": "EDY STEPHANE",
        "dateNaissMembre": "1997-11-30T00:00:00.000Z",
        "lieuNaissMembre": "YACOLO",
        "sexeMembre": "F",
        "emailMembre": "email3@example.com",
        "nationaliteMembre": "Ivoirienne",
        "fonctionMembre": "0574313410",
        "contactMembre": "Contact 1",
        "ethnieMembre": "Bété",
        "residenceMembre": "Sicogi",
        "civiliteMembre": "Monsieur",
        "dateConversionMembre": "2005-09-10T00:00:00.000Z",
        "baptemeEauMembre": "OUI",
        "dateBaptemeMembre": "2010-03-18T00:00:00.000Z",
        "dateMariageMembre": null,
        "capaciteSpirituelleMembre": "Bonne",
        "situationMatrimonialeMembre": "Célibataire",
        "nombreEnfantMembre": 0,
        "photoMembre": null,
        "lieuBaptemeEauMembre": "YOP GARE",
        "contactParentMembre": "Contact Parent 3",
        "baptemeSaintEspritMembre": "OUI",
        "dateBaptemeSaintEspritMembre": "2015-11-22T00:00:00.000Z",
        "egliseOrigineMembre": "Église Origine 3",
        "nomPrenomParentMembre": "Parent 3",
        "lieuTravailMembre": "SPIDER TECHNOLOGIES",
        "idNiveauEtude": null,
        "idEglise": null,
        "idCellule": null,
        "idDepartement": null,
        "idGroupe": null,
        "idResponsabilite": null,
        "idDomaineActivite": null,
        "idUtilisateur": null
    },
    {
        "idMembre": 36,
        "nomMembre": "DIGBEU",
        "prenomMembre": "EDY STEPHANE",
        "dateNaissMembre": "1997-11-30T00:00:00.000Z",
        "lieuNaissMembre": "YACOLO",
        "sexeMembre": "F",
        "emailMembre": "email3@example.com",
        "nationaliteMembre": "Ivoirienne",
        "fonctionMembre": "0574313410",
        "contactMembre": "Contact 1",
        "ethnieMembre": "Bété",
        "residenceMembre": "Sicogi",
        "civiliteMembre": "Monsieur",
        "dateConversionMembre": "2005-09-10T00:00:00.000Z",
        "baptemeEauMembre": "OUI",
        "dateBaptemeMembre": "2010-03-18T00:00:00.000Z",
        "dateMariageMembre": null,
        "capaciteSpirituelleMembre": "Bonne",
        "situationMatrimonialeMembre": "Célibataire",
        "nombreEnfantMembre": 0,
        "photoMembre": null,
        "lieuBaptemeEauMembre": "YOP GARE",
        "contactParentMembre": "Contact Parent 3",
        "baptemeSaintEspritMembre": "OUI",
        "dateBaptemeSaintEspritMembre": "2015-11-22T00:00:00.000Z",
        "egliseOrigineMembre": "Église Origine 3",
        "nomPrenomParentMembre": "Parent 3",
        "lieuTravailMembre": "SPIDER TECHNOLOGIES",
        "idNiveauEtude": null,
        "idEglise": null,
        "idCellule": null,
        "idDepartement": null,
        "idGroupe": null,
        "idResponsabilite": null,
        "idDomaineActivite": null,
        "idUtilisateur": null
    },
    {
        "idMembre": 37,
        "nomMembre": "DIGBEU",
        "prenomMembre": "EDY STEPHANE",
        "dateNaissMembre": "1997-11-30T00:00:00.000Z",
        "lieuNaissMembre": "YACOLO",
        "sexeMembre": "F",
        "emailMembre": "email3@example.com",
        "nationaliteMembre": "Ivoirienne",
        "fonctionMembre": "0574313410",
        "contactMembre": "Contact 1",
        "ethnieMembre": "Bété",
        "residenceMembre": "Sicogi",
        "civiliteMembre": "Monsieur",
        "dateConversionMembre": "2005-09-10T00:00:00.000Z",
        "baptemeEauMembre": "OUI",
        "dateBaptemeMembre": "2010-03-18T00:00:00.000Z",
        "dateMariageMembre": null,
        "capaciteSpirituelleMembre": "Bonne",
        "situationMatrimonialeMembre": "Célibataire",
        "nombreEnfantMembre": 0,
        "photoMembre": null,
        "lieuBaptemeEauMembre": "YOP GARE",
        "contactParentMembre": "Contact Parent 3",
        "baptemeSaintEspritMembre": "OUI",
        "dateBaptemeSaintEspritMembre": "2015-11-22T00:00:00.000Z",
        "egliseOrigineMembre": "Église Origine 3",
        "nomPrenomParentMembre": "Parent 3",
        "lieuTravailMembre": "SPIDER TECHNOLOGIES",
        "idNiveauEtude": null,
        "idEglise": null,
        "idCellule": null,
        "idDepartement": null,
        "idGroupe": null,
        "idResponsabilite": null,
        "idDomaineActivite": null,
        "idUtilisateur": null
    },
    {
        "idMembre": 38,
        "nomMembre": "DIGBEU",
        "prenomMembre": "EDY STEPHANE",
        "dateNaissMembre": "1997-11-30T00:00:00.000Z",
        "lieuNaissMembre": "YACOLO",
        "sexeMembre": "F",
        "emailMembre": "email3@example.com",
        "nationaliteMembre": "Ivoirienne",
        "fonctionMembre": "0574313410",
        "contactMembre": "Contact 1",
        "ethnieMembre": "Bété",
        "residenceMembre": "Sicogi",
        "civiliteMembre": "Monsieur",
        "dateConversionMembre": "2005-09-10T00:00:00.000Z",
        "baptemeEauMembre": "OUI",
        "dateBaptemeMembre": "2010-03-18T00:00:00.000Z",
        "dateMariageMembre": null,
        "capaciteSpirituelleMembre": "Bonne",
        "situationMatrimonialeMembre": "Célibataire",
        "nombreEnfantMembre": 0,
        "photoMembre": null,
        "lieuBaptemeEauMembre": "YOP GARE",
        "contactParentMembre": "Contact Parent 3",
        "baptemeSaintEspritMembre": "OUI",
        "dateBaptemeSaintEspritMembre": "2015-11-22T00:00:00.000Z",
        "egliseOrigineMembre": "Église Origine 3",
        "nomPrenomParentMembre": "Parent 3",
        "lieuTravailMembre": "SPIDER TECHNOLOGIES",
        "idNiveauEtude": null,
        "idEglise": null,
        "idCellule": null,
        "idDepartement": null,
        "idGroupe": null,
        "idResponsabilite": null,
        "idDomaineActivite": null,
        "idUtilisateur": null
    },
    {
        "idMembre": 39,
        "nomMembre": "DIGBEU",
        "prenomMembre": "EDY STEPHANE",
        "dateNaissMembre": "1997-11-30T00:00:00.000Z",
        "lieuNaissMembre": "YACOLO",
        "sexeMembre": "F",
        "emailMembre": "email3@example.com",
        "nationaliteMembre": "Ivoirienne",
        "fonctionMembre": "0574313410",
        "contactMembre": "Contact 1",
        "ethnieMembre": "Bété",
        "residenceMembre": "Sicogi",
        "civiliteMembre": "Monsieur",
        "dateConversionMembre": "2005-09-10T00:00:00.000Z",
        "baptemeEauMembre": "OUI",
        "dateBaptemeMembre": "2010-03-18T00:00:00.000Z",
        "dateMariageMembre": null,
        "capaciteSpirituelleMembre": "Bonne",
        "situationMatrimonialeMembre": "Célibataire",
        "nombreEnfantMembre": 0,
        "photoMembre": null,
        "lieuBaptemeEauMembre": "YOP GARE",
        "contactParentMembre": "Contact Parent 3",
        "baptemeSaintEspritMembre": "OUI",
        "dateBaptemeSaintEspritMembre": "2015-11-22T00:00:00.000Z",
        "egliseOrigineMembre": "Église Origine 3",
        "nomPrenomParentMembre": "Parent 3",
        "lieuTravailMembre": "SPIDER TECHNOLOGIES",
        "idNiveauEtude": null,
        "idEglise": null,
        "idCellule": null,
        "idDepartement": null,
        "idGroupe": null,
        "idResponsabilite": null,
        "idDomaineActivite": null,
        "idUtilisateur": null
    },
    {
        "idMembre": 40,
        "nomMembre": "DIGBEU",
        "prenomMembre": "EDY STEPHANE",
        "dateNaissMembre": "1997-11-30T00:00:00.000Z",
        "lieuNaissMembre": "YACOLO",
        "sexeMembre": "F",
        "emailMembre": "email3@example.com",
        "nationaliteMembre": "Ivoirienne",
        "fonctionMembre": "0574313410",
        "contactMembre": "Contact 1",
        "ethnieMembre": "Bété",
        "residenceMembre": "Sicogi",
        "civiliteMembre": "Monsieur",
        "dateConversionMembre": "2005-09-10T00:00:00.000Z",
        "baptemeEauMembre": "OUI",
        "dateBaptemeMembre": "2010-03-18T00:00:00.000Z",
        "dateMariageMembre": null,
        "capaciteSpirituelleMembre": "Bonne",
        "situationMatrimonialeMembre": "Célibataire",
        "nombreEnfantMembre": 0,
        "photoMembre": null,
        "lieuBaptemeEauMembre": "YOP GARE",
        "contactParentMembre": "Contact Parent 3",
        "baptemeSaintEspritMembre": "OUI",
        "dateBaptemeSaintEspritMembre": "2015-11-22T00:00:00.000Z",
        "egliseOrigineMembre": "Église Origine 3",
        "nomPrenomParentMembre": "Parent 3",
        "lieuTravailMembre": "SPIDER TECHNOLOGIES",
        "idNiveauEtude": null,
        "idEglise": null,
        "idCellule": null,
        "idDepartement": null,
        "idGroupe": null,
        "idResponsabilite": null,
        "idDomaineActivite": null,
        "idUtilisateur": null
    },
    {
        "idMembre": 41,
        "nomMembre": "COULIBALY",
        "prenomMembre": "JEAN MICHAEL",
        "dateNaissMembre": "1997-11-30T00:00:00.000Z",
        "lieuNaissMembre": "YABAYO",
        "sexeMembre": "F",
        "emailMembre": "email3@example.com",
        "nationaliteMembre": "Ivoirienne",
        "fonctionMembre": "Medecin",
        "contactMembre": "014755000",
        "ethnieMembre": "Bété",
        "residenceMembre": "Sicogi",
        "civiliteMembre": "Monsieur",
        "dateConversionMembre": "2005-09-10T00:00:00.000Z",
        "baptemeEauMembre": "OUI",
        "dateBaptemeMembre": "2010-03-18T00:00:00.000Z",
        "dateMariageMembre": null,
        "capaciteSpirituelleMembre": "Bonne",
        "situationMatrimonialeMembre": "Célibataire",
        "nombreEnfantMembre": 0,
        "photoMembre": null,
        "lieuBaptemeEauMembre": "YOP GARE",
        "contactParentMembre": "0789514410",
        "baptemeSaintEspritMembre": "OUI",
        "dateBaptemeSaintEspritMembre": "2015-11-22T00:00:00.000Z",
        "egliseOrigineMembre": "Église Origine 3",
        "nomPrenomParentMembre": "Parent 3",
        "lieuTravailMembre": "MOOV",
        "idNiveauEtude": null,
        "idEglise": null,
        "idCellule": null,
        "idDepartement": null,
        "idGroupe": null,
        "idResponsabilite": null,
        "idDomaineActivite": null,
        "idUtilisateur": null
    },
    {
        "idMembre": 42,
        "nomMembre": "MEDAO",
        "prenomMembre": "LARISSA",
        "dateNaissMembre": "1997-11-30T00:00:00.000Z",
        "lieuNaissMembre": "YABAYO",
        "sexeMembre": "F",
        "emailMembre": "medao@gmail.com",
        "nationaliteMembre": "Ivoirienne",
        "fonctionMembre": "Medecin",
        "contactMembre": "014755000",
        "ethnieMembre": "Avickam",
        "residenceMembre": "Andokoi Chateau",
        "civiliteMembre": "Monsieur",
        "dateConversionMembre": "2005-09-10T00:00:00.000Z",
        "baptemeEauMembre": "OUI",
        "dateBaptemeMembre": "2010-03-18T00:00:00.000Z",
        "dateMariageMembre": null,
        "capaciteSpirituelleMembre": "Bonne",
        "situationMatrimonialeMembre": "Célibataire",
        "nombreEnfantMembre": 0,
        "photoMembre": null,
        "lieuBaptemeEauMembre": "YOP GARE",
        "contactParentMembre": "0789514410",
        "baptemeSaintEspritMembre": "OUI",
        "dateBaptemeSaintEspritMembre": "2015-11-22T00:00:00.000Z",
        "egliseOrigineMembre": "Église Origine 3",
        "nomPrenomParentMembre": "GBASE",
        "lieuTravailMembre": "MOOV",
        "idNiveauEtude": null,
        "idEglise": null,
        "idCellule": null,
        "idDepartement": null,
        "idGroupe": null,
        "idResponsabilite": null,
        "idDomaineActivite": null,
        "idUtilisateur": null
    },
    {
        "idMembre": 43,
        "nomMembre": "KOUAME",
        "prenomMembre": "JEAN YVES",
        "dateNaissMembre": "1995-10-12T00:00:00.000Z",
        "lieuNaissMembre": "KOUMASSI",
        "sexeMembre": "M",
        "emailMembre": "medao@gmail.com",
        "nationaliteMembre": "Ivoirienne",
        "fonctionMembre": "Artiste",
        "contactMembre": "014755000",
        "ethnieMembre": "Avickam",
        "residenceMembre": "Andokoi Chateau",
        "civiliteMembre": "Monsieur",
        "dateConversionMembre": "2005-09-10T00:00:00.000Z",
        "baptemeEauMembre": "OUI",
        "dateBaptemeMembre": "2010-03-18T00:00:00.000Z",
        "dateMariageMembre": null,
        "capaciteSpirituelleMembre": "Bonne",
        "situationMatrimonialeMembre": "Célibataire",
        "nombreEnfantMembre": 0,
        "photoMembre": null,
        "lieuBaptemeEauMembre": "YOP GARE",
        "contactParentMembre": "0789514410",
        "baptemeSaintEspritMembre": "OUI",
        "dateBaptemeSaintEspritMembre": "2015-11-22T00:00:00.000Z",
        "egliseOrigineMembre": "METHODISTE",
        "nomPrenomParentMembre": "GBASSE JEAN MICHAEL",
        "lieuTravailMembre": "SODECI",
        "idNiveauEtude": 1,
        "idEglise": 2,
        "idCellule": 1,
        "idDepartement": 2,
        "idGroupe": null,
        "idResponsabilite": null,
        "idDomaineActivite": null,
        "idUtilisateur": 1
    },
    {
        "idMembre": 44,
        "nomMembre": "KOUAME",
        "prenomMembre": "JEAN YVES",
        "dateNaissMembre": "1995-10-12T00:00:00.000Z",
        "lieuNaissMembre": "KOUMASSI",
        "sexeMembre": "M",
        "emailMembre": "medao@gmail.com",
        "nationaliteMembre": "Ivoirienne",
        "fonctionMembre": "Artiste",
        "contactMembre": "014755000",
        "ethnieMembre": "Avickam",
        "residenceMembre": "Andokoi Chateau",
        "civiliteMembre": "Monsieur",
        "dateConversionMembre": "2005-09-10T00:00:00.000Z",
        "baptemeEauMembre": "OUI",
        "dateBaptemeMembre": "2010-03-18T00:00:00.000Z",
        "dateMariageMembre": null,
        "capaciteSpirituelleMembre": "Bonne",
        "situationMatrimonialeMembre": "Célibataire",
        "nombreEnfantMembre": 0,
        "photoMembre": null,
        "lieuBaptemeEauMembre": "YOP GARE",
        "contactParentMembre": "0789514410",
        "baptemeSaintEspritMembre": "OUI",
        "dateBaptemeSaintEspritMembre": "2015-11-22T00:00:00.000Z",
        "egliseOrigineMembre": "METHODISTE",
        "nomPrenomParentMembre": "GBASSE JEAN MICHAEL",
        "lieuTravailMembre": "SODECI",
        "idNiveauEtude": 1,
        "idEglise": 2,
        "idCellule": 1,
        "idDepartement": 2,
        "idGroupe": 3,
        "idResponsabilite": 2,
        "idDomaineActivite": 2,
        "idUtilisateur": 1
    },
    {
        "idMembre": 45,
        "nomMembre": "Adiobo",
        "prenomMembre": "Marie Paule",
        "dateNaissMembre": "1992-05-21T00:00:00.000Z",
        "lieuNaissMembre": "Toumodi",
        "sexeMembre": "M",
        "emailMembre": "mariepaule@gmail.com",
        "nationaliteMembre": "Ivoirienne",
        "fonctionMembre": "Directrice générale",
        "contactMembre": "0789854122",
        "ethnieMembre": "Baoulé",
        "residenceMembre": "Cocody angré",
        "civiliteMembre": "Mademoiselle",
        "dateConversionMembre": "2005-09-10T00:00:00.000Z",
        "baptemeEauMembre": "OUI",
        "dateBaptemeMembre": "2010-03-18T00:00:00.000Z",
        "dateMariageMembre": null,
        "capaciteSpirituelleMembre": "Bonne",
        "situationMatrimonialeMembre": "Célibataire",
        "nombreEnfantMembre": 0,
        "photoMembre": null,
        "lieuBaptemeEauMembre": "Yopougon gare",
        "contactParentMembre": "0564820016",
        "baptemeSaintEspritMembre": "OUI",
        "dateBaptemeSaintEspritMembre": "2016-11-22T00:00:00.000Z",
        "egliseOrigineMembre": "Église Origine 3",
        "nomPrenomParentMembre": "Parent 3",
        "lieuTravailMembre": "UEFHB",
        "idNiveauEtude": 1,
        "idEglise": 1,
        "idCellule": null,
        "idDepartement": null,
        "idGroupe": null,
        "idResponsabilite": null,
        "idDomaineActivite": null,
        "idUtilisateur": 5
    },
    {
        "idMembre": 46,
        "nomMembre": "KOUAME",
        "prenomMembre": "JEAN YVES",
        "dateNaissMembre": "1995-10-12T00:00:00.000Z",
        "lieuNaissMembre": "KOUMASSI",
        "sexeMembre": "M",
        "emailMembre": "medao@gmail.com",
        "nationaliteMembre": "Ivoirienne",
        "fonctionMembre": "Artiste",
        "contactMembre": "014755000",
        "ethnieMembre": "Avickam",
        "residenceMembre": "Andokoi Chateau",
        "civiliteMembre": "Monsieur",
        "dateConversionMembre": "2005-09-10T00:00:00.000Z",
        "baptemeEauMembre": "OUI",
        "dateBaptemeMembre": "2010-03-18T00:00:00.000Z",
        "dateMariageMembre": null,
        "capaciteSpirituelleMembre": "Bonne",
        "situationMatrimonialeMembre": "Célibataire",
        "nombreEnfantMembre": 0,
        "photoMembre": null,
        "lieuBaptemeEauMembre": "YOP GARE",
        "contactParentMembre": "0789514410",
        "baptemeSaintEspritMembre": "OUI",
        "dateBaptemeSaintEspritMembre": "2015-11-22T00:00:00.000Z",
        "egliseOrigineMembre": "METHODISTE",
        "nomPrenomParentMembre": "GBASSE JEAN MICHAEL",
        "lieuTravailMembre": "SODECI",
        "idNiveauEtude": 1,
        "idEglise": 2,
        "idCellule": 1,
        "idDepartement": 2,
        "idGroupe": 3,
        "idResponsabilite": 2,
        "idDomaineActivite": 2,
        "idUtilisateur": 2
    },
    {
        "idMembre": 47,
        "nomMembre": "Adiobo",
        "prenomMembre": "Marie Paule",
        "dateNaissMembre": "1992-05-21T00:00:00.000Z",
        "lieuNaissMembre": "Toumodi",
        "sexeMembre": "M",
        "emailMembre": "mariepaule@gmail.com",
        "nationaliteMembre": "Ivoirienne",
        "fonctionMembre": "Directrice générale",
        "contactMembre": "0789854122",
        "ethnieMembre": "Baoulé",
        "residenceMembre": "Cocody angré",
        "civiliteMembre": "Mademoiselle",
        "dateConversionMembre": "2005-09-10T00:00:00.000Z",
        "baptemeEauMembre": "OUI",
        "dateBaptemeMembre": "2010-03-18T00:00:00.000Z",
        "dateMariageMembre": null,
        "capaciteSpirituelleMembre": "Bonne",
        "situationMatrimonialeMembre": "Célibataire",
        "nombreEnfantMembre": 0,
        "photoMembre": null,
        "lieuBaptemeEauMembre": "Yopougon gare",
        "contactParentMembre": "0564820016",
        "baptemeSaintEspritMembre": "OUI",
        "dateBaptemeSaintEspritMembre": "2016-11-22T00:00:00.000Z",
        "egliseOrigineMembre": "Église Origine 3",
        "nomPrenomParentMembre": "Parent 3",
        "lieuTravailMembre": "UEFHB",
        "idNiveauEtude": 1,
        "idEglise": null,
        "idCellule": null,
        "idDepartement": null,
        "idGroupe": null,
        "idResponsabilite": 1,
        "idDomaineActivite": null,
        "idUtilisateur": 1
    },
    {
        "idMembre": 48,
        "nomMembre": "Adiobo",
        "prenomMembre": "Marie Paule",
        "dateNaissMembre": "1992-05-21T00:00:00.000Z",
        "lieuNaissMembre": "Toumodi",
        "sexeMembre": "M",
        "emailMembre": "mariepaule@gmail.com",
        "nationaliteMembre": "Ivoirienne",
        "fonctionMembre": "Directrice générale",
        "contactMembre": "0789854122",
        "ethnieMembre": "Baoulé",
        "residenceMembre": "Cocody angré",
        "civiliteMembre": "Mademoiselle",
        "dateConversionMembre": "2005-09-10T00:00:00.000Z",
        "baptemeEauMembre": "OUI",
        "dateBaptemeMembre": "2010-03-18T00:00:00.000Z",
        "dateMariageMembre": null,
        "capaciteSpirituelleMembre": "Bonne",
        "situationMatrimonialeMembre": "Célibataire",
        "nombreEnfantMembre": 0,
        "photoMembre": null,
        "lieuBaptemeEauMembre": "Yopougon gare",
        "contactParentMembre": "0564820016",
        "baptemeSaintEspritMembre": "OUI",
        "dateBaptemeSaintEspritMembre": "2016-11-22T00:00:00.000Z",
        "egliseOrigineMembre": "Église Origine 3",
        "nomPrenomParentMembre": "Parent 3",
        "lieuTravailMembre": "UEFHB",
        "idNiveauEtude": 1,
        "idEglise": null,
        "idCellule": null,
        "idDepartement": null,
        "idGroupe": null,
        "idResponsabilite": 1,
        "idDomaineActivite": null,
        "idUtilisateur": 1
    }
]

